version: 1.0.{build}
configuration: Release
platform: Any CPU
before_build:
- nuget restore
build:
  project: /src/OpenWeatherMap.sln
  verbosity: minimal
deploy: off
notifications:
- provider: Email
  to:
  - caronjoan@gmail.com
  subject: OpenWeatherMap-Api-Net Build
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
